language: go

sudo: true

services:
    - docker

matrix:
  include:
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: tip
  allow_failures:
    - go: tip

script:
  - docker-compose run api go get -t -v
  - docker-compose run api go test -v
