version: '2'

services:

    haproxy:
        build: ./docker/haproxy/
        container_name: chat_haproxy
        links:
            - api

    db:
        build: ./docker/scylla/
        container_name: chat_db
        volumes:
            - ./storage/dump:/dump

    api:
        build: ./docker/golang/
        container_name: chat_api1
        restart: always
        volumes:
            - ..:/go
        links:
            - db
