version: '2'

services:
    db:
        build: ./docker/scylla/
        container_name: chat_db
        volumes:
            - ./storage/dump:/dump

    api:
        build: ./docker/golang/
        container_name: chat_api1
        restart: always
        command: go run api.go db.go conversation.go sentence.go
        volumes:
            - ./api:/go
        links:
            - db

    #website:
    #    build: ./docker/website/
    #    container_name: chat_website
    #    volumes:
    #        - ./website:/usr/share/nginx/html

    #haproxy:
    #    build: ./docker/haproxy/
    #    container_name: chat_haproxy
    #    links:
    #        - api01
